AOT-Technologies/forms-flow-ai-extensions

- camunda-formio-tasklist-vue/src/components/TaskList.vue
#496: Added a class to formio tag. rest fix is done in Service BC
> [service-flow: #496] CCII - Feedback - The Q - Attach Document view is not functioning correctly- component side fix

- camunda-formio-tasklist-vue/.eslintrc.js
- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/mixins/BaseMixin.vue
- camunda-formio-tasklist-vue/src/components/mixins/TaskListMixin.vue
- camunda-formio-tasklist-vue/src/views/TaskList.vue
Bug fix
JIRA: 
- Remove userName prop to get the details from keycloak token details
- Update package-lock to fix security vulnerabilities
- Tested the change along with @abilpraju-aot  and ensured claim userName is working and localstorage details are being stored.
> Hotfix to remove username prop

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: FWF-585
- Adding relevant CSS styles and adding those classes to the TaskList component
Manual Verification
- When an assignee already exists (screenshot looks similar when there's a Claim button instead)
- On clicking assignee
The right hand side needs a major revamp of CSS style for consistency and easier maintenance.
> FWF-585 Adjusting assignee icons to look similar to react component

- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA- https://aottech.atlassian.net/browse/FWF-511
> [vue][forms-flow-ai-extensions-#511]-TOOLTIP FIX

- camunda-formio-tasklist-vue/package-lock.json
> Fix merge conflicts

- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklistSearch.scss
JIRA STORY-: 
1) https://aottech.atlassian.net/browse/FWF-511 
2) https://aottech.atlassian.net/browse/FWF-583
3) https://aottech.atlassian.net/browse/FWF-588
> CSS FIXES- INCIDENT FORM, TOOLTIP, DROPDOWN PADDING

- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/main.ts
- camunda-formio-tasklist-vue/src/services/SocketIOServices.ts
- camunda-formio-tasklist-vue/src/services/TasklistTypes.ts
- camunda-formio-tasklist-vue/src/services/axios.ts
- camunda-formio-tasklist-vue/src/services/camunda-rest.ts
- camunda-formio-tasklist-vue/src/services/constants.ts
- camunda-formio-tasklist-vue/src/services/format-time.ts
- camunda-formio-tasklist-vue/src/services/formio-token.ts
- camunda-formio-tasklist-vue/src/services/formsflowai-api.ts
- camunda-formio-tasklist-vue/src/services/get-formio.ts
- camunda-formio-tasklist-vue/src/services/search-constants.ts
- camunda-formio-tasklist-vue/src/services/utils.ts
- camunda-formio-tasklist-vue/src/shims-bpmn-js.d.ts
- camunda-formio-tasklist-vue/src/shims-tsx.d.ts
- camunda-formio-tasklist-vue/src/shims-vue.d.ts
- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklistSearch.scss
1. FWF 505
2. FWF 511
3. FWF 583
4.FWF  588
> [vue][forms-flow-ai-extensions- #505 #505 #583 #588] - limit list to formsflow-reviewers and css fixes

- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/package.json
- camunda-formio-tasklist-vue/src/components/TaskHistory.vue
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/addons/ExpandContract.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
- camunda-formio-tasklist-vue/src/main.ts
- camunda-formio-tasklist-vue/src/services/camunda-rest.ts
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: 
FWF-505
FWF-555
FWF-616
1. Added placeholder for Claim userlist
2. Add API endpoints for generic UserList component.
3. Remove bootstrap-icons package
4. Replace Expand/Contract icons with arrows icons in font-awesome
5. Upgrade Vue to latest version 2.6.14
6. Tooltip for Removing due date and followup date
Replace Expand/Contract icons with arrows icons in font-awesome
> Tasklist changes

- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: FWF-585
- Alignment corrections around claim user icon and assignee.
Firefox and Chrome, different window sizes
Firefox - Full Size
Firefox - Small Size
Chrome - Full Size
Chrome - Small Size
> FWF-585 Claim User Icon corrections

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
1. #FWF-625 -CSS- VIEW SUBMISSION NOT SHOWING UP
2. latest upstream
> [web][forms-flow-ai-extensions-#FWF-625] CSS- VIEW SUBMISSION NOT SHOWING UP

- camunda-formio-tasklist-vue/src/services/SocketIOServices.ts
- camunda-formio-tasklist-vue/src/views/TaskList.vue
[web][Websockets - Vue] Reconnect logic to be implemented (#49)
> [web][Websockets - Vue] Reconnect logic to be implemented (#49)

- camunda-formio-tasklist-vue/CHANGELOG.md
- camunda-formio-tasklist-vue/package-lock.json
- Create ChangeLog file
- Update package-lock.json
> CHANGELOG file

- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/package.json
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
What are the main changes in PR?
1. updated the version
2. removed typo
> Dev to master

- camunda-formio-tasklist-vue/.eslintrc.js
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/index.js
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/interfaces/index.ts
- camunda-formio-tasklist-vue/src/interfaces/state-interface.ts
- camunda-formio-tasklist-vue/src/router/index.ts
- camunda-formio-tasklist-vue/src/services/SocketIOServices.ts
- camunda-formio-tasklist-vue/src/services/camunda-rest.ts
- camunda-formio-tasklist-vue/src/services/constants.ts
- camunda-formio-tasklist-vue/src/services/utils.ts
- camunda-formio-tasklist-vue/src/store/index.ts
- camunda-formio-tasklist-vue/src/store/modules/index.ts
- camunda-formio-tasklist-vue/src/store/modules/serviceFlow-module.ts
- camunda-formio-tasklist-vue/src/store/state/index.ts
- camunda-formio-tasklist-vue/src/store/state/state-model.ts
- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklistSearch.scss
- camunda-formio-tasklist-vue/vue.config.js
JIRA: 
1. https://aottech.atlassian.net/browse/FWF-774
2. https://aottech.atlassian.net/browse/FWF-775
3. .https://aottech.atlassian.net/browse/FWF-776
4. https://aottech.atlassian.net/browse/FWF-777
5. https://aottech.atlassian.net/browse/FWF-782
6. https://aottech.atlassian.net/browse/FWF-783
7. https://aottech.atlassian.net/browse/FWF-784
8. https://aottech.atlassian.net/browse/FWF-793
9. https://aottech.atlassian.net/browse/FWF-790
10. https://aottech.atlassian.net/browse/FWF-789
11. https://aottech.atlassian.net/browse/FWF-788
What are the main changes in PR?
fixed active form getting reset when there is a new WebSocket event, multiple reloading of form, CSS fixes
> [vue]-[hotfixes] ixed active form getting reset when there is a new WebSocket event, multiple reloading of form, CSS fixes

- camunda-formio-tasklist-vue/src/App.vue
JIRA: 
https://aottech.atlassian.net/browse/FWF-807 about the change that a reviewer would benefit from etc.-->
> [vue][service-flow-#807]-clicking groups area shifts screen

- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/search/TaskListSearch.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-805
> [vue][service-flow-#805]-Tasks area seems to wrap more than in formsflow.ai

- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/src/App.vue
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-806
https://aottech.atlassian.net/browse/FWF-834
ScreenShot:
> [vue][service-flow-#806, #834]-vue- alignment issue

- camunda-formio-tasklist-vue/src/components/FormListModal.vue
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-808
> [vue][service-flow-#808] vue-filter dropdown

- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-846
> [vue] css fix

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/services/camunda-rest.ts
- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
> Task filter changes

- camunda-formio-tasklist-vue/.eslintrc.js
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/sort/TaskListSort.vue
- camunda-formio-tasklist-vue/src/components/sort/TaskListSortoptions.vue
- camunda-formio-tasklist-vue/src/models/FormRequestActionPayload.ts
- camunda-formio-tasklist-vue/src/models/FormRequestPayload.ts
- camunda-formio-tasklist-vue/src/models/sorting.ts
- camunda-formio-tasklist-vue/src/services/constants.ts
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: 852, 609
- Support search by lastname, firstName, email
- Make on searching assignee toggle faster
- Add Tasklist Sorting component
@ann-aot - Athira had spotted a bug in searching functionality in simple search by lastName. The search happening in Vue-select component instead of calling Camunda API. So on searching lastName for `John Doe`, even searching by firstName was returning the result.
Ticket Details:
https://aottech.atlassian.net/browse/FWF-853
> FWF-852, FWF-609

- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/sort/TaskListSort.vue
- camunda-formio-tasklist-vue/src/components/sort/TaskListSortoptions.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
JIRA: 
https://aottech.atlassian.net/browse/FWF-857
> [vue][service-flow-#857]-css- reduce the space before and after the filter labels

- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOFormList.scss
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
> add css changes for FormList

- camunda-formio-tasklist-vue/src/models/Payload.ts
> updated import

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/models/Auth.ts
- camunda-formio-tasklist-vue/src/models/index.ts
- camunda-formio-tasklist-vue/src/services/auth.ts
- camunda-formio-tasklist-vue/src/services/formio-token.ts
- camunda-formio-tasklist-vue/src/services/index.ts
- camunda-formio-tasklist-vue/src/styles/user-styles.css
JIRA: 
https://aottech.atlassian.net/browse/FWF-872
only user who is in `FORM_IO_REVIEWER` in keylock is allowed to TaskList access
> [vue][service-flow-#872 ] show message if no access

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/models/Auth.ts
- camunda-formio-tasklist-vue/src/models/index.ts
- camunda-formio-tasklist-vue/src/services/auth.ts
- camunda-formio-tasklist-vue/src/services/formio-token.ts
- camunda-formio-tasklist-vue/src/services/index.ts
- camunda-formio-tasklist-vue/src/styles/user-styles.css
[vue][service-flow-#872 ] show a message if no access (#100)
> [vue][service-flow-#872 ] show message if no access (#100)

- camunda-formio-tasklist-vue/src/components/TaskList.vue
JIRA: https://aottech.atlassian.net/browse/FWF-549
> Process Diagram First click showing blank diagram

- camunda-formio-tasklist-vue/docs/components/TaskList.md
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/styles/camundaFormIOTasklist.scss
Reverts AOT-Technologies/forms-flow-ai-extensions#114
> Revert "Mobile View is Broken"

- camunda-formio-tasklist-vue/src/components/TaskList.vue
JIRA: 
https://aottech.atlassian.net/browse/FWF-966
added logic for custom, events, now clients can add their custom events in the form. and custom event receive the call in their application, eg, 
call custom events from the form
receive in the client application
> [vue][service-flow-#966] custom events added for client

- camunda-formio-tasklist-vue/src/components/search/TaskListSearch.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
- camunda-formio-tasklist-vue/src/models/SearchOptions.ts
> Master to Dev PR

- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
> tooltip updated

- camunda-formio-tasklist-vue/src/components/search/TaskListSearch.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
> updated x closing problem in Search component

- .gitignore
> Minor change

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/package.json
> V1.0.19 vupdate

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/services/GetFormio.ts
> Use regex for getting formid & submissionId (refactor)

- camunda-formio-tasklist-vue/src/components/search/TaskListAddSearchIgnoreCase.vue
- camunda-formio-tasklist-vue/src/components/search/TaskListSearch.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
> Fixed taskfilter

- camunda-formio-tasklist-vue/src/components/FormViewSubmission.vue
* updated task filter
* updated formio api url
* updated const file
* hard code url removed
* updated form io url
* eslint updated
* fixed history view
JIRA:
> History View Submisisons fix (#150)

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
> CHANGLELOG for v1.0.19

- .github/pull_request_template.md
- camunda-formio-tasklist-vue/docs/StyleGuide.md
- camunda-formio-tasklist-vue/docs/WebCustomEvents.md
> :book: add docs on PR guidelines (#155)

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/views/TaskList.vue
> Clearing dev issues

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/mixins/BaseMixin.vue
- camunda-formio-tasklist-vue/src/views/TaskList.vue
> combinedProps

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
- camunda-formio-tasklist-vue/docs/components/TaskList.md
> updated document with formio changes and disabled porps

- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
> Shuhaib aot patch 2

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
- camunda-formio-tasklist-vue/docs/components/TaskList.md
- camunda-formio-tasklist-vue/package.json
> removed duplicate

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
- camunda-formio-tasklist-vue/docs/components/TaskList.md
- camunda-formio-tasklist-vue/package.json
> updated version of package

- camunda-formio-tasklist-vue/docs/components/TaskList.md
> Clear conflict

- camunda-formio-tasklist-vue/docs/components/TaskList.md
> Fixed bugs and released

- camunda-formio-tasklist-vue/src/components/TaskList.vue
JIRA: 
1.task list groups UI updated with text truncate
> Group UI change

- camunda-formio-tasklist-vue/src/components/TaskList.vue
JIRA: 
updated task assignee filter
> updated with task assignee edit

- .github/workflows/camunda-formio-tasklist-vue-cd.yml
- .github/workflows/camunda-formio-tasklist-vue-ci.yml
- .github/workflows/camunda-formio-tasklist-vue.yml
Thank you for submitting a PR to forms-flow-ai-extensions!
To ease the process of reviewing your PR, do make sure to complete the following boxes.
JIRA: https://aottech.atlassian.net/browse/FWF-1197
CD Action for automated deployment to npm registry
Github Action
> CD for camunda task list

- camunda-formio-tasklist-vue/package.json
- camunda-formio-tasklist-vue/src/mixins/BaseMixin.vue
> removed Buffer.from and added old code

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
JIRA: 
1. follow up date 
2. due date 
(these changes are implemented on task details and filter task)
> updated follow up date and due date

- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
JIRA: 
1.filter task after before select option fixed
> Due  followup date

- camunda-formio-tasklist-vue/README.md
> updated with css variable

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
> Fixed task variable issue

- camunda-formio-tasklist-vue/src/components/form/FormList.vue
- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
- camunda-formio-tasklist-vue/src/services/Axios.ts
- camunda-formio-tasklist-vue/src/services/CamundaRest.ts
> Authorization api change

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/form/FormList.vue
- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/search/TaskListSearch.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
- camunda-formio-tasklist-vue/src/services/Axios.ts
- camunda-formio-tasklist-vue/src/services/CamundaRest.ts
- camunda-formio-tasklist-vue/src/shims-tsx.d.ts
- camunda-formio-tasklist-vue/src/styles/user-styles.css
> Process variable added to filter task

- camunda-formio-tasklist-vue/README.md
- camunda-formio-tasklist-vue/docs/CHANGELOG.md
- camunda-formio-tasklist-vue/package.json
- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/form/FormList.vue
- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/search/TaskListSearch.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
- camunda-formio-tasklist-vue/src/services/Axios.ts
- camunda-formio-tasklist-vue/src/services/CamundaRest.ts
- camunda-formio-tasklist-vue/src/shims-tsx.d.ts
- camunda-formio-tasklist-vue/src/styles/user-styles.css
> Conflict remove

- camunda-formio-tasklist-vue/src/services/SearchOptions.ts
> updated with data type and like oprator

- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
> fixed List Height static value

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
JIRA: 
1. task variable on left side task list 👍 it will list the task variable in same order which displaying on camunda
> updated task list variable order

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/search/TaskListAddSearchIgnoreCase.vue
> Console error fixed

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/layout/Header.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
- camunda-formio-tasklist-vue/src/services/SearchOptions.ts
> Task variable

- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
> Task Name issue fix

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
> vue warn fixed

- camunda-formio-tasklist-vue/src/components/taskVariable/TaskVariable.vue
- camunda-formio-tasklist-vue/src/services/SearchOptions.ts
1. fixed value on like operator
> Like operator fixed

- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
> Fahad aot patch 3

- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/core/RobotManager.java
- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/core/robot/IRobotService.java
- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/core/robot/RCCService.java
- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/core/robot/RobocorpCloudService.java
- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/data/entity/RobotHandlerAudit.java
- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/handlers/IRobotHandler.java
- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/handlers/impl/BackgroundCheckRobotHandler.java
- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/handlers/impl/WebScraperRobotHandler.java
- rpa-robocorp-extention/external-client-extention/src/main/resources/db/changelog/db-changelog-master.xml
> robocorp cloud changes

- rpa-robocorp-extention/external-client-extention/src/main/java/org/camunda/rpa/client/core/io/RobotResponseService.java
> Robocorp cloud

- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
> btn ui fixed

- camunda-formio-tasklist-vue/src/components/layout/RightSider.vue
JIRA: 
1.Now follow up date and due date can modify using datepicker
> followup & due date modified

- camunda-formio-tasklist-vue/src/router/index.ts
> lazy loading implemented for better perfomance

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
> change log

- camunda-formio-tasklist-vue/package.json
> New version

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
- camunda-formio-tasklist-vue/src/services/SearchOptions.ts
> New Release 🍃 

- .github/workflows/camunda-formio-tasklist-vue-cd.yml
Npm will be public on pull request from Vue-dev branch
JIRA: 
The cd process will be on pull request from Vue-dev branch
> fixed the cd process

- .github/workflows/formsflow-custom-formio-cd.yml
> Install dev dependencies in CD github workflow.

- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
- camunda-formio-tasklist-vue/src/components/layout/Pagination.vue
> added new event called resetValue to start from 1

- camunda-formio-tasklist-vue/src/components/TaskList.vue
- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
- camunda-formio-tasklist-vue/src/components/layout/LeftSider.vue
- camunda-formio-tasklist-vue/src/components/layout/Pagination.vue
- camunda-formio-tasklist-vue/src/main.ts
- camunda-formio-tasklist-vue/src/models/ApplicationCreatePayload.ts
> 🐛 fixed form list and submission

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
- camunda-formio-tasklist-vue/src/components/form/FormListModal.vue
> 🐛 modal close updated

- camunda-formio-tasklist-vue/package.json
> updated package version

- camunda-formio-tasklist-vue/docs/CHANGELOG.md
- camunda-formio-tasklist-vue/package-lock.json
- camunda-formio-tasklist-vue/package.json
- camunda-formio-tasklist-vue/src/components/layout/RightSider.vue
- camunda-formio-tasklist-vue/src/components/search/TaskSearchItem.vue
JIRA: 
1. Remove the v-calender package and its dependencies.
> Removed v-calender package
